### ISSUE TITLE
Incompatible with complex background shorthand

### ISSUE THREAD

**Issue by diagramatics** [ben-eb/postcss-resemble-image#8]
Let's say I have this code:

```css
background: resemble-image(url("foo.png")) no-repeat 75% center / cover;
```

This would be generated into:

```css
background: url("foo.png"), linear-gradient(90deg, #161e2a 0%, #1a2331 25%, #5c4e52 50%, #584b4f 75%) no-repeat 75% center / cover;
```

Which would invalidate it.

Now I can think of either making the parser work by detecting commas to know when to put the fallback in (or just whack it at the end of the value with a `,` prefix, or wrap the whole long shorthand value into the `resemble-image` function itself. I guess this would be your call on how to proceed 😄

**Comment by ben-eb** [comment]
I like the first option (add it to the end of the declaration). Would you like to send a pull request for this? Essentially we need to change it so that [this line](https://github.com/ben-eb/postcss-resemble-image/blob/master/src/index.js#L47) does not add the gradient to the `url` function, but instead we should push a new node with the gradient into the AST.

I can help out if you would like to do this!
